CREATE TABLE `cidade` (
  `CIDADE` int(11) NOT NULL AUTO_INCREMENT,
  `DESCRICAO_CIDADE` varchar(50) NOT NULL,
  `UF` varchar(2) NOT NULL,
  `PAIS` varchar(30) NOT NULL,
  `CEP_BASICO` varchar(10) DEFAULT NULL,
  `DDD` varchar(7) DEFAULT NULL,
  PRIMARY KEY (`CIDADE`),
  UNIQUE KEY `ID_UNIQUE` (`CIDADE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `empresa` (
  `EMPRESA` int(11) NOT NULL AUTO_INCREMENT,
  `NOME_FANTASIA` varchar(30) NOT NULL,
  `RAZAO_SOCIAL` varchar(50) NOT NULL,
  `ENDERECO` varchar(50) NOT NULL,
  `BAIRRO` varchar(30) NOT NULL,
  `CEP` varchar(10) NOT NULL,
  `CIDADE` int(11) NOT NULL,
  `TELEFONE` varchar(15) NOT NULL,
  `FAX` varchar(15) DEFAULT NULL,
  `CNPJ` varchar(18) NOT NULL,
  `IE` varchar(18) DEFAULT NULL,
  `ATIVO` tinyint(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`EMPRESA`),
  UNIQUE KEY `EMPRESA_UNIQUE` (`EMPRESA`),
  KEY `EmpresaXCidade_idx` (`CIDADE`),
  CONSTRAINT `EmpresaXCidade` FOREIGN KEY (`CIDADE`) REFERENCES `cidade` (`CIDADE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `tipo_complemento` (
  `IDTIPOCOMPLEMENTO` int(11) NOT NULL AUTO_INCREMENT,
  `TIPO_COMPLEMENTO` varchar(3) NOT NULL,
  `DESCRICAO_TIPO_COMPLEMENTO` varchar(30) NOT NULL,
  `EMPRESA` int(11) NOT NULL,
  PRIMARY KEY (`IDTIPOCOMPLEMENTO`),
  UNIQUE KEY `IDTIPOCOMPLEMENTO_UNIQUE` (`IDTIPOCOMPLEMENTO`),
  KEY `TipoComplementoXEmpresa_idx` (`EMPRESA`),
  CONSTRAINT `TipoComplementoXEmpresa` FOREIGN KEY (`EMPRESA`) REFERENCES `empresa` (`EMPRESA`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `grupo_produto` (
  `GRUPO_PRODUTO` int(11) NOT NULL AUTO_INCREMENT,
  `DESCRICAO_GRUPO_PRODUTO` varchar(50) NOT NULL,
  `PERC_DESCONTO` decimal(5,2) NOT NULL,
  `TIPO_COMPLEMENTO` int(11) NOT NULL,
  `EMPRESA` int(11) NOT NULL,
  PRIMARY KEY (`GRUPO_PRODUTO`),
  UNIQUE KEY `GRUPO_PRODUTO_UNIQUE` (`GRUPO_PRODUTO`),
  KEY `GrupoXTipoComplemento_idx` (`TIPO_COMPLEMENTO`),
  KEY `GrupoXEmpresa_idx` (`EMPRESA`),
  CONSTRAINT `GrupoXEmpresa` FOREIGN KEY (`EMPRESA`) REFERENCES `empresa` (`EMPRESA`) ON DELETE CASCADE,
  CONSTRAINT `GrupoXTipoComplemento` FOREIGN KEY (`TIPO_COMPLEMENTO`) REFERENCES `tipo_complemento` (`IDTIPOCOMPLEMENTO`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `produto` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PRODUTO` varchar(15) NOT NULL,
  `DESCRICAO_PRODUTO` varchar(250) NOT NULL,
  `APELIDO_PRODUTO` varchar(100) NOT NULL,
  `GRUPO_PRODUTO` int(11) NOT NULL,
  `SUBGRUPO_PRODUTO` int(11) NOT NULL,
  `SITUACAO` varchar(1) NOT NULL,
  `PESO_LIQUIDO` decimal(11,3) NOT NULL,
  `CLASSIFICACAO_FISCAL` varchar(10) NOT NULL,
  `CODIGO_BARRAS` varchar(50) NOT NULL,
  `COLECAO` varchar(100) NOT NULL,
  `EMPRESA` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`),
  KEY `ProdutoXGrupo_idx` (`GRUPO_PRODUTO`,`SUBGRUPO_PRODUTO`),
  KEY `ProdutoXSubGrupo_idx` (`SUBGRUPO_PRODUTO`),
  KEY `ProdutoXEmpresa_idx` (`EMPRESA`),
  CONSTRAINT `ProdutoXEmpresa` FOREIGN KEY (`EMPRESA`) REFERENCES `empresa` (`EMPRESA`) ON DELETE CASCADE,
  CONSTRAINT `ProdutoXGrupo` FOREIGN KEY (`GRUPO_PRODUTO`) REFERENCES `grupo_produto` (`GRUPO_PRODUTO`) ON DELETE CASCADE,
  CONSTRAINT `ProdutoXSubGrupo` FOREIGN KEY (`SUBGRUPO_PRODUTO`) REFERENCES `grupo_produto` (`GRUPO_PRODUTO`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci


SELECT * FROM cidade;
INSERT INTO cidade (DESCRICAO_CIDADE, UF, PAIS, CEP_BASICO, DDD) VALUES ('Birigui', 'SP', 'BR', '16200-001', '18');
INSERT INTO cidade (DESCRICAO_CIDADE, UF, PAIS, CEP_BASICO, DDD) VALUES ('Araçatuba', 'SP', 'BR', '16000-001', '18');

SELECT * FROM empresa;
INSERT INTO empresa (NOME_FANTASIA, RAZAO_SOCIAL, ENDERECO, BAIRRO, CEP, CIDADE, TELEFONE, FAX, CNPJ, IE) VALUES ('Trovata', 'TROVATA INF, CONS. E SIS. LTDA', 'Avenida Nelson Calixto, 142', 'Novo Parque São Vicente', '16200-320', 1, '(18) 3644-7333', NULL, '10.647.137/0001-96', NULL);
INSERT INTO empresa (NOME_FANTASIA, RAZAO_SOCIAL, ENDERECO, BAIRRO, CEP, CIDADE, TELEFONE, FAX, CNPJ, IE) VALUES ('Ofoco', 'Robson Pratti Gonçalves', 'Rua Aviação, 1253 - Bloco 800 - Ap 822', 'Chácaras Patrimônio Santana', '16056-873', 2, '(18) 98199-7242', NULL, '82.541.353/0001-63', NULL);

SELECT * FROM tipo_complemento;
INSERT INTO tipo_complemento (TIPO_COMPLEMENTO, DESCRICAO_TIPO_COMPLEMENTO, EMPRESA) VALUES ('TPC', 'Tipo de complemento', 1);

SELECT * FROM grupo_produto;
INSERT INTO grupo_produto (DESCRICAO_GRUPO_PRODUTO, PERC_DESCONTO, TIPO_COMPLEMENTO, EMPRESA) VALUES ('Nenhum', '0', 1, 1);
INSERT INTO grupo_produto (DESCRICAO_GRUPO_PRODUTO, PERC_DESCONTO, TIPO_COMPLEMENTO, EMPRESA) VALUES ('GRUPO 1 - 10', '0.05', 1, 1);
INSERT INTO grupo_produto (DESCRICAO_GRUPO_PRODUTO, PERC_DESCONTO, TIPO_COMPLEMENTO, EMPRESA) VALUES ('GRUPO 10 - 20', '0.10', 1, 1);
INSERT INTO grupo_produto (DESCRICAO_GRUPO_PRODUTO, PERC_DESCONTO, TIPO_COMPLEMENTO, EMPRESA) VALUES ('GRUPO 20 - 50', '0.20', 1, 1);
INSERT INTO grupo_produto (DESCRICAO_GRUPO_PRODUTO, PERC_DESCONTO, TIPO_COMPLEMENTO, EMPRESA) VALUES ('GRUPO 50 - 100', '0.30', 1, 1);
INSERT INTO grupo_produto (DESCRICAO_GRUPO_PRODUTO, PERC_DESCONTO, TIPO_COMPLEMENTO, EMPRESA) VALUES ('GRUPO 100 mais', '0.40', 1, 1);

SELECT * FROM produto;
INSERT INTO produto (PRODUTO, DESCRICAO_PRODUTO, APELIDO_PRODUTO, GRUPO_PRODUTO, SUBGRUPO_PRODUTO, SITUACAO, PESO_LIQUIDO, CLASSIFICACAO_FISCAL, CODIGO_BARRAS, COLECAO, EMPRESA) VALUES ('PRODUTO 01', 'DESCRICAO DO PRODUTO', 'PRODUTO 01 - TENIS FEMININO', 1, 1, 'S', 0, '', '', '', 1);
INSERT INTO produto (PRODUTO, DESCRICAO_PRODUTO, APELIDO_PRODUTO, GRUPO_PRODUTO, SUBGRUPO_PRODUTO, SITUACAO, PESO_LIQUIDO, CLASSIFICACAO_FISCAL, CODIGO_BARRAS, COLECAO, EMPRESA) VALUES ('PRODUTO 02', 'DESCRICAO DO PRODUTO', 'PRODUTO 02 - TENIS MASCULINO', 1, 1, 'S', 0, '', '', '', 1);
INSERT INTO produto (PRODUTO, DESCRICAO_PRODUTO, APELIDO_PRODUTO, GRUPO_PRODUTO, SUBGRUPO_PRODUTO, SITUACAO, PESO_LIQUIDO, CLASSIFICACAO_FISCAL, CODIGO_BARRAS, COLECAO, EMPRESA) VALUES ('PRODUTO 03', 'DESCRICAO DO PRODUTO', 'PRODUTO 03 - TENIS CRIANÇA', 1, 1, 'S', 0, '', '', '', 1);
INSERT INTO produto (PRODUTO, DESCRICAO_PRODUTO, APELIDO_PRODUTO, GRUPO_PRODUTO, SUBGRUPO_PRODUTO, SITUACAO, PESO_LIQUIDO, CLASSIFICACAO_FISCAL, CODIGO_BARRAS, COLECAO, EMPRESA) VALUES ('PRODUTO 04', 'DESCRICAO DO PRODUTO', 'PRODUTO 04 - TENIS FEMININO', 1, 1, 'S', 0, '', '', '', 1);
INSERT INTO produto (PRODUTO, DESCRICAO_PRODUTO, APELIDO_PRODUTO, GRUPO_PRODUTO, SUBGRUPO_PRODUTO, SITUACAO, PESO_LIQUIDO, CLASSIFICACAO_FISCAL, CODIGO_BARRAS, COLECAO, EMPRESA) VALUES ('PRODUTO 05', 'DESCRICAO DO PRODUTO', 'PRODUTO 05 - TENIS MASCULINO', 1, 1, 'S', 0, '', '', '', 1);
INSERT INTO produto (PRODUTO, DESCRICAO_PRODUTO, APELIDO_PRODUTO, GRUPO_PRODUTO, SUBGRUPO_PRODUTO, SITUACAO, PESO_LIQUIDO, CLASSIFICACAO_FISCAL, CODIGO_BARRAS, COLECAO, EMPRESA) VALUES ('PRODUTO 06', 'DESCRICAO DO PRODUTO', 'PRODUTO 06 - TENIS CRIANÇA', 1, 1, 'S', 0, '', '', '', 1);
INSERT INTO produto (PRODUTO, DESCRICAO_PRODUTO, APELIDO_PRODUTO, GRUPO_PRODUTO, SUBGRUPO_PRODUTO, SITUACAO, PESO_LIQUIDO, CLASSIFICACAO_FISCAL, CODIGO_BARRAS, COLECAO, EMPRESA) VALUES ('PRODUTO 07', 'DESCRICAO DO PRODUTO', 'PRODUTO 07 - TENIS FEMININO', 1, 1, 'S', 0, '', '', '', 1);
INSERT INTO produto (PRODUTO, DESCRICAO_PRODUTO, APELIDO_PRODUTO, GRUPO_PRODUTO, SUBGRUPO_PRODUTO, SITUACAO, PESO_LIQUIDO, CLASSIFICACAO_FISCAL, CODIGO_BARRAS, COLECAO, EMPRESA) VALUES ('PRODUTO 08', 'DESCRICAO DO PRODUTO', 'PRODUTO 08 - TENIS MASCULINO', 1, 1, 'S', 0, '', '', '', 1);
INSERT INTO produto (PRODUTO, DESCRICAO_PRODUTO, APELIDO_PRODUTO, GRUPO_PRODUTO, SUBGRUPO_PRODUTO, SITUACAO, PESO_LIQUIDO, CLASSIFICACAO_FISCAL, CODIGO_BARRAS, COLECAO, EMPRESA) VALUES ('PRODUTO 09', 'DESCRICAO DO PRODUTO', 'PRODUTO 09 - TENIS CRIANÇA', 1, 1, 'S', 0, '', '', '', 1);
INSERT INTO produto (PRODUTO, DESCRICAO_PRODUTO, APELIDO_PRODUTO, GRUPO_PRODUTO, SUBGRUPO_PRODUTO, SITUACAO, PESO_LIQUIDO, CLASSIFICACAO_FISCAL, CODIGO_BARRAS, COLECAO, EMPRESA) VALUES ('PRODUTO 10', 'DESCRICAO DO PRODUTO', 'PRODUTO 10 - TENIS FEMININO', 1, 1, 'S', 0, '', '', '', 1);
INSERT INTO produto (PRODUTO, DESCRICAO_PRODUTO, APELIDO_PRODUTO, GRUPO_PRODUTO, SUBGRUPO_PRODUTO, SITUACAO, PESO_LIQUIDO, CLASSIFICACAO_FISCAL, CODIGO_BARRAS, COLECAO, EMPRESA) VALUES ('PRODUTO 11', 'DESCRICAO DO PRODUTO', 'PRODUTO 11 - TENIS MASCULINO', 1, 1, 'S', 0, '', '', '', 1);
INSERT INTO produto (PRODUTO, DESCRICAO_PRODUTO, APELIDO_PRODUTO, GRUPO_PRODUTO, SUBGRUPO_PRODUTO, SITUACAO, PESO_LIQUIDO, CLASSIFICACAO_FISCAL, CODIGO_BARRAS, COLECAO, EMPRESA) VALUES ('PRODUTO 12', 'DESCRICAO DO PRODUTO', 'PRODUTO 12 - TENIS CRIANÇA', 1, 1, 'S', 0, '', '', '', 1);